### ISSUE TITLE
installing in a stand alone c9sdk

### ISSUE THREAD

**Issue by rimmartin** [invokr/c9.ide.language.cpp#7]
Hi,
I got nodejs 6.2 and the npm install clang_tool part compiled and installed.
But when I go to put this plugin intp client-default.js (e.g. in line 289)  must not be doing it right.

What is put in?  line 289 doesn't make any sense to me.

I work with a lot of c++ and am interested in finding what I could possibly add to this plugin after getting it to run

**Comment by rimmartin** [comment]
Oh I installed clang-tool from github; just 2 days ago it was nicely updated for nodejs 6.2 and it seems to work

**Comment by invokr** [comment]
So is your issue solved? To activate the plugin simply add it to the config. See this file: https://github.com/c9/core/blob/master/configs/client-default.js#L323. Just copy the marked line, and change it to c9.ide.lanague.cpp/cpp.

There is also a docker container who's Dockerfile has all the commands in it to run c9 and the plugin on ubuntu: https://hub.docker.com/r/invokr/cloud9-cpp/~/dockerfile/

**Comment by rimmartin** [comment]
not resolved; thanks for being around Saturday:-)
I put the line    "plugins/c9.ide.language.cpp/cpp", in and the browser view sits with spinner and doesn't come up.  Take it back out and the browser view stands up.

Not sure what I'm doing different than https://github.com/invokr/c9.ide.language.cpp#installation-on-a-local-c9v3-instance

**Comment by invokr** [comment]
Hey, sorry for taking six days to respond to you.
I triggered a docker build of c9 + the plugin when I last read your issue, see [here](https://hub.docker.com/r/invokr/cloud9-cpp/). I just pulled and tried the build and everything seems to be working fine.

Please have a look at the [Dockerfile](https://hub.docker.com/r/invokr/cloud9-cpp/%7E/dockerfile/) which has all the instructions required to install C9 and the plugin on a Ubuntu instance. Notable differences are:
- Node v0.12 is used instead of 6.1
- The last version of the clang submodule on npm is a bit older than the repository version, this might be why it's working with v0.12 but not 6.1
