### ISSUE TITLE
Running on c9.io

### ISSUE THREAD

**Issue by arekzaluski** [invokr/c9.ide.language.cpp#8]
Is there any plan to fix this plugin for live c9.io ? It will be great to have autocompletion for c++.

**Comment by invokr** [comment]
I'm not sure it's possible to fix it as I don't even know the reason it's crashing in the first place.

I suspect that the language worker is evaluated in a different context (in this case the underlying docker container) as the workspace. The Node Module only gets installed in the workspace, hence the worker crashed because it can't find the module.

Without any access to their underlying system I can't even debug this properly. The plugin works fine with the standalone version though, I'm using it all the time.
